services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8080
    environment:
      - SERVER_PORT=8080
      - REDIS_ADDR=redis:6379
      - REDIS_DB=0
      - REDIS_PASSWORD=
    depends_on:
      - redis
    networks:
      - app-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_BASE=http://localhost:8000
    networks:
      - app-network
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
